[build]
  command = "npm ci && npm run build"
  publish = ".next"

[context.production.environment]
  # Ensure the canonical site URL is set for NextAuth and metadata
  NEXTAUTH_URL = "https://quickeats8.netlify.app"
