import { Zone, Restaurant, DeliveryPartner } from '@/types';

// Mock Zones - Lucknow Areas
export const zones: Zone[] = [
  {
    id: 'zone-1',
    name: 'Hazratganj',
    surgeMultiplier: 1.2,
    deliveryPartnersAvailable: 45,
    ordersInZone: 82,
    estimatedWait: 28,
  },
  {
    id: 'zone-2',
    name: 'Gomti Nagar',
    surgeMultiplier: 1.5,
    deliveryPartnersAvailable: 32,
    ordersInZone: 156,
    estimatedWait: 35,
  },
  {
    id: 'zone-3',
    name: 'Indira Nagar',
    surgeMultiplier: 1.8,
    deliveryPartnersAvailable: 18,
    ordersInZone: 201,
    estimatedWait: 42,
  },
  {
    id: 'zone-4',
    name: 'Charbagh',
    surgeMultiplier: 1.9,
    deliveryPartnersAvailable: 12,
    ordersInZone: 234,
    estimatedWait: 48,
  },
  {
    id: 'zone-5',
    name: 'Alambagh',
    surgeMultiplier: 1.3,
    deliveryPartnersAvailable: 38,
    ordersInZone: 94,
    estimatedWait: 30,
  },
  {
    id: 'zone-6',
    name: 'Aminabad',
    surgeMultiplier: 1.4,
    deliveryPartnersAvailable: 35,
    ordersInZone: 128,
    estimatedWait: 32,
  },
  {
    id: 'zone-7',
    name: 'Chowk',
    surgeMultiplier: 1.6,
    deliveryPartnersAvailable: 28,
    ordersInZone: 176,
    estimatedWait: 38,
  },
  {
    id: 'zone-8',
    name: 'Aliganj',
    surgeMultiplier: 1.2,
    deliveryPartnersAvailable: 42,
    ordersInZone: 76,
    estimatedWait: 26,
  },
  {
    id: 'zone-9',
    name: 'Mahanagar',
    surgeMultiplier: 1.35,
    deliveryPartnersAvailable: 40,
    ordersInZone: 112,
    estimatedWait: 31,
  },
  {
    id: 'zone-10',
    name: 'Rajajipuram',
    surgeMultiplier: 1.7,
    deliveryPartnersAvailable: 22,
    ordersInZone: 184,
    estimatedWait: 40,
  },
];

// Mock Restaurants - Lucknow Favorites
export const restaurants: Restaurant[] = [
  {
    id: 'r-1',
    name: 'Dastarkhwan',
    cuisine: 'Awadhi',
    image: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=500&h=300&fit=crop',
    rating: 4.9,
    deliveryFee: 40,
    deliveryTime: 28,
    zone: 'zone-1',
    status: 'open',
    menu: [
      { id: 'm-1', name: 'Awadhi Biryani', description: 'Authentic Lucknow biryani', price: 420, vegetarian: false, spicyLevel: 2 },
      { id: 'm-2', name: 'Galauti Kebab', description: 'Melt-in-mouth kebab', price: 380, vegetarian: false, spicyLevel: 1 },
      { id: 'm-3', name: 'Sheermal', description: 'Traditional saffron bread', price: 120, vegetarian: true, spicyLevel: 0 },
    ],
  },
  {
    id: 'r-2',
    name: 'Tunday Kababi',
    cuisine: 'Lucknowi Kebabs',
    image: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=500&h=300&fit=crop',
    rating: 4.8,
    deliveryFee: 50,
    deliveryTime: 30,
    zone: 'zone-1',
    status: 'open',
    menu: [
      { id: 'm-4', name: 'Tunday Galauti Kebab', description: 'Famous melt-in-mouth kebab', price: 350, vegetarian: false, spicyLevel: 1 },
      { id: 'm-5', name: 'Seekh Kebab', description: 'Minced meat on skewers', price: 300, vegetarian: false, spicyLevel: 2 },
      { id: 'm-6', name: 'Paratha', description: 'Flaky Indian bread', price: 80, vegetarian: true, spicyLevel: 1 },
    ],
  },
  {
    id: 'r-3',
    name: 'Behrouz Biryani',
    cuisine: 'Biryani',
    image: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=500&h=300&fit=crop',
    rating: 4.7,
    deliveryFee: 45,
    deliveryTime: 32,
    zone: 'zone-2',
    status: 'open',
    menu: [
      { id: 'm-7', name: 'Chicken Biryani', description: 'Fragrant basmati rice with chicken', price: 380, vegetarian: false, spicyLevel: 2 },
      { id: 'm-8', name: 'Mutton Biryani', description: 'Premium mutton biryani', price: 480, vegetarian: false, spicyLevel: 3 },
      { id: 'm-9', name: 'Veg Biryani', description: 'Mixed vegetables biryani', price: 280, vegetarian: true, spicyLevel: 1 },
    ],
  },
  {
    id: 'r-4',
    name: 'Royal Café',
    cuisine: 'North Indian',
    image: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=500&h=300&fit=crop',
    rating: 4.6,
    deliveryFee: 35,
    deliveryTime: 26,
    zone: 'zone-3',
    status: 'open',
    menu: [
      { id: 'm-10', name: 'Butter Chicken', description: 'Creamy tomato base', price: 350, vegetarian: false, spicyLevel: 2 },
      { id: 'm-11', name: 'Dal Makhani', description: 'Creamy lentil curry', price: 300, vegetarian: true, spicyLevel: 1 },
      { id: 'm-12', name: 'Tandoori Chicken', description: 'Marinated and grilled', price: 400, vegetarian: false, spicyLevel: 3 },
    ],
  },
  {
    id: 'r-5',
    name: 'Curry Leaf',
    cuisine: 'South Indian',
    image: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=500&h=300&fit=crop',
    rating: 4.7,
    deliveryFee: 30,
    deliveryTime: 25,
    zone: 'zone-2',
    status: 'open',
    menu: [
      { id: 'm-13', name: 'Idli Sambar', description: 'Steamed rice cakes with lentil curry', price: 120, vegetarian: true, spicyLevel: 1 },
      { id: 'm-14', name: 'Masala Dosa', description: 'Crispy crepes with masala filling', price: 150, vegetarian: true, spicyLevel: 2 },
      { id: 'm-15', name: 'Vada Pav', description: 'Fried potato fritter with bread', price: 80, vegetarian: true, spicyLevel: 1 },
    ],
  },
  {
    id: 'r-6',
    name: 'Barbeque Nation',
    cuisine: 'BBQ & Grills',
    image: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=500&h=300&fit=crop',
    rating: 4.8,
    deliveryFee: 60,
    deliveryTime: 35,
    zone: 'zone-4',
    status: 'open',
    menu: [
      { id: 'm-16', name: 'Tandoori Paneer', description: 'Grilled cottage cheese', price: 320, vegetarian: true, spicyLevel: 2 },
      { id: 'm-17', name: 'Grilled Fish', description: 'Marinated and grilled', price: 450, vegetarian: false, spicyLevel: 2 },
      { id: 'm-18', name: 'Chicken Tikka', description: 'Spiced chicken chunks', price: 380, vegetarian: false, spicyLevel: 2 },
    ],
  },
  {
    id: 'r-7',
    name: 'Marksmen Café',
    cuisine: 'Café & Bistro',
    image: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=500&h=300&fit=crop',
    rating: 4.5,
    deliveryFee: 40,
    deliveryTime: 20,
    zone: 'zone-1',
    status: 'open',
    menu: [
      { id: 'm-19', name: 'Espresso', description: 'Strong Italian coffee', price: 150, vegetarian: true, spicyLevel: 0 },
      { id: 'm-20', name: 'Croissant', description: 'Buttery French pastry', price: 120, vegetarian: true, spicyLevel: 0 },
      { id: 'm-21', name: 'Club Sandwich', description: 'Triple-layered sandwich', price: 280, vegetarian: false, spicyLevel: 0 },
    ],
  },
  {
    id: 'r-8',
    name: 'Domino\'s Pizza',
    cuisine: 'Italian',
    image: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=500&h=300&fit=crop',
    rating: 4.6,
    deliveryFee: 50,
    deliveryTime: 30,
    zone: 'zone-3',
    status: 'open',
    menu: [
      { id: 'm-22', name: 'Pepperoni Pizza', description: 'Classic pizza with pepperoni', price: 450, vegetarian: false, spicyLevel: 1 },
      { id: 'm-23', name: 'Margherita Pizza', description: 'Cheese and tomato pizza', price: 380, vegetarian: true, spicyLevel: 0 },
      { id: 'm-24', name: 'Veggie Pizza', description: 'Fresh vegetables on crust', price: 350, vegetarian: true, spicyLevel: 0 },
    ],
  },
  {
    id: 'r-9',
    name: 'Pizza Hut',
    cuisine: 'Italian',
    image: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=500&h=300&fit=crop',
    rating: 4.5,
    deliveryFee: 60,
    deliveryTime: 35,
    zone: 'zone-2',
    status: 'open',
    menu: [
      { id: 'm-25', name: 'Pan Pizza', description: 'Thick crust pizza', price: 420, vegetarian: false, spicyLevel: 1 },
      { id: 'm-26', name: 'New Hand Tossed', description: 'Thin crust pizza', price: 380, vegetarian: true, spicyLevel: 0 },
      { id: 'm-27', name: 'Cheese Garlic Bread', description: 'Cheesy garlic bread', price: 150, vegetarian: true, spicyLevel: 0 },
    ],
  },
  {
    id: 'r-10',
    name: 'KFC',
    cuisine: 'Fast Food',
    image: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=500&h=300&fit=crop',
    rating: 4.4,
    deliveryFee: 45,
    deliveryTime: 25,
    zone: 'zone-4',
    status: 'open',
    menu: [
      { id: 'm-28', name: 'Fried Chicken', description: 'Crispy fried chicken', price: 250, vegetarian: false, spicyLevel: 1 },
      { id: 'm-29', name: 'Chicken Wings', description: 'Spiced chicken wings', price: 200, vegetarian: false, spicyLevel: 2 },
      { id: 'm-30', name: 'Zinger Burger', description: 'Spicy chicken burger', price: 220, vegetarian: false, spicyLevel: 2 },
    ],
  },
  {
    id: 'r-11',
    name: 'Pind Balluchi',
    cuisine: 'Punjabi',
    image: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=500&h=300&fit=crop',
    rating: 4.7,
    deliveryFee: 50,
    deliveryTime: 30,
    zone: 'zone-5',
    status: 'open',
    menu: [
      { id: 'm-31', name: 'Chole Bhature', description: 'Fried bread with curry', price: 200, vegetarian: true, spicyLevel: 2 },
      { id: 'm-32', name: 'Paneer Tikka', description: 'Grilled cottage cheese', price: 320, vegetarian: true, spicyLevel: 2 },
      { id: 'm-33', name: 'Sarson da Saag', description: 'Mustard greens curry', price: 280, vegetarian: true, spicyLevel: 1 },
    ],
  },
  {
    id: 'r-12',
    name: 'Biryani House',
    cuisine: 'Hyderabadi',
    image: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=500&h=300&fit=crop',
    rating: 4.8,
    deliveryFee: 45,
    deliveryTime: 35,
    zone: 'zone-6',
    status: 'open',
    menu: [
      { id: 'm-34', name: 'Hyderabadi Biryani', description: 'Traditional biryani', price: 420, vegetarian: false, spicyLevel: 2 },
      { id: 'm-35', name: 'Paneer Biryani', description: 'Cottage cheese biryani', price: 320, vegetarian: true, spicyLevel: 1 },
      { id: 'm-36', name: 'Dum Pukht Murgh', description: 'Slow-cooked chicken', price: 380, vegetarian: false, spicyLevel: 2 },
    ],
  },
  {
    id: 'r-13',
    name: 'Chai Ki Dukan',
    cuisine: 'Street Food',
    image: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=500&h=300&fit=crop',
    rating: 4.3,
    deliveryFee: 20,
    deliveryTime: 15,
    zone: 'zone-7',
    status: 'busy',
    menu: [
      { id: 'm-37', name: 'Samosa', description: 'Crispy pastry with filling', price: 30, vegetarian: true, spicyLevel: 1 },
      { id: 'm-38', name: 'Kachori', description: 'Spiced fried pastry', price: 40, vegetarian: true, spicyLevel: 2 },
      { id: 'm-39', name: 'Chai', description: 'Hot Indian tea', price: 20, vegetarian: true, spicyLevel: 0 },
    ],
  },
  {
    id: 'r-14',
    name: 'Wok Express',
    cuisine: 'Asian',
    image: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=500&h=300&fit=crop',
    rating: 4.6,
    deliveryFee: 50,
    deliveryTime: 30,
    zone: 'zone-8',
    status: 'open',
    menu: [
      { id: 'm-40', name: 'Chicken Hakka Noodles', description: 'Stir-fried noodles', price: 280, vegetarian: false, spicyLevel: 2 },
      { id: 'm-41', name: 'Vegetable Fried Rice', description: 'Mixed vegetables with rice', price: 220, vegetarian: true, spicyLevel: 1 },
      { id: 'm-42', name: 'Manchurian', description: 'Spiced vegetable balls', price: 250, vegetarian: true, spicyLevel: 2 },
    ],
  },
  {
    id: 'r-15',
    name: 'Momos Corner',
    cuisine: 'Tibetan',
    image: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=500&h=300&fit=crop',
    rating: 4.7,
    deliveryFee: 35,
    deliveryTime: 25,
    zone: 'zone-9',
    status: 'open',
    menu: [
      { id: 'm-43', name: 'Chicken Momos', description: 'Steamed dumplings', price: 150, vegetarian: false, spicyLevel: 1 },
      { id: 'm-44', name: 'Veg Momos', description: 'Steamed vegetable dumplings', price: 120, vegetarian: true, spicyLevel: 1 },
      { id: 'm-45', name: 'Fried Momos', description: 'Crispy fried dumplings', price: 160, vegetarian: false, spicyLevel: 1 },
    ],
  },
  {
    id: 'r-16',
    name: 'Kake Da Dhaba',
    cuisine: 'Punjabi Street Food',
    image: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=500&h=300&fit=crop',
    rating: 4.5,
    deliveryFee: 35,
    deliveryTime: 32,
    zone: 'zone-10',
    status: 'open',
    menu: [
      { id: 'm-46', name: 'Pav Bhaji', description: 'Mashed vegetables with bread', price: 150, vegetarian: true, spicyLevel: 2 },
      { id: 'm-47', name: 'Aloo Parantha', description: 'Potato stuffed bread', price: 120, vegetarian: true, spicyLevel: 1 },
      { id: 'm-48', name: 'Chole Kulche', description: 'Chickpea curry with bread', price: 130, vegetarian: true, spicyLevel: 2 },
    ],
  },
  {
    id: 'r-17',
    name: 'Spice Route',
    cuisine: 'Indian Fusion',
    image: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=500&h=300&fit=crop',
    rating: 4.4,
    deliveryFee: 55,
    deliveryTime: 38,
    zone: 'zone-1',
    status: 'open',
    menu: [
      { id: 'm-49', name: 'Tikka Pasta', description: 'Fusion of Indian spices and pasta', price: 380, vegetarian: false, spicyLevel: 2 },
      { id: 'm-50', name: 'Tandoori Fish', description: 'Grilled fish with spices', price: 520, vegetarian: false, spicyLevel: 2 },
      { id: 'm-51', name: 'Paneer Tikka Masala Pasta', description: 'Creamy fusion dish', price: 420, vegetarian: true, spicyLevel: 1 },
    ],
  },
  {
    id: 'r-18',
    name: 'Sushi Paradise',
    cuisine: 'Japanese',
    image: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=500&h=300&fit=crop',
    rating: 4.8,
    deliveryFee: 80,
    deliveryTime: 40,
    zone: 'zone-2',
    status: 'open',
    menu: [
      { id: 'm-52', name: 'California Roll', description: 'Crab and avocado roll', price: 350, vegetarian: false, spicyLevel: 0 },
      { id: 'm-53', name: 'Vegetable Roll', description: 'Mixed vegetable roll', price: 280, vegetarian: true, spicyLevel: 0 },
      { id: 'm-54', name: 'Dragon Roll', description: 'Premium combination roll', price: 450, vegetarian: false, spicyLevel: 1 },
    ],
  },
  {
    id: 'r-19',
    name: 'Thali Express',
    cuisine: 'Indian Thali',
    image: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=500&h=300&fit=crop',
    rating: 4.7,
    deliveryFee: 55,
    deliveryTime: 36,
    zone: 'zone-3',
    status: 'open',
    menu: [
      { id: 'm-55', name: 'Gujarati Thali', description: 'Complete vegetarian meal', price: 320, vegetarian: true, spicyLevel: 1 },
      { id: 'm-56', name: 'Rajasthani Thali', description: 'Traditional royal meal', price: 380, vegetarian: false, spicyLevel: 2 },
      { id: 'm-57', name: 'South Indian Thali', description: 'Complete South Indian meal', price: 300, vegetarian: true, spicyLevel: 1 },
    ],
  },
  {
    id: 'r-20',
    name: 'Choco Lava',
    cuisine: 'Desserts & Bakery',
    image: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=500&h=300&fit=crop',
    rating: 4.9,
    deliveryFee: 30,
    deliveryTime: 18,
    zone: 'zone-4',
    status: 'open',
    menu: [
      { id: 'm-58', name: 'Chocolate Lava Cake', description: 'Molten chocolate cake', price: 180, vegetarian: true, spicyLevel: 0 },
      { id: 'm-59', name: 'Cheesecake', description: 'Creamy cheesecake', price: 200, vegetarian: true, spicyLevel: 0 },
      { id: 'm-60', name: 'Brownies', description: 'Rich chocolate brownies', price: 150, vegetarian: true, spicyLevel: 0 },
    ],
  },
];

// Mock Delivery Partners - 20 Realistic North Indian Names
export const deliveryPartners: DeliveryPartner[] = [
  {
    id: 'p-1',
    name: 'Rajesh Kumar',
    vehicle: 'Bike',
    rating: 4.9,
    totalDeliveries: 1240,
    zone: 'zone-1',
    status: 'available',
    earnings: 125000,
    image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&h=100&fit=crop',
  },
  {
    id: 'p-2',
    name: 'Amit Sharma',
    vehicle: 'Bike',
    rating: 4.7,
    totalDeliveries: 980,
    zone: 'zone-2',
    status: 'busy',
    earnings: 98000,
    image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&h=100&fit=crop',
  },
  {
    id: 'p-3',
    name: 'Vikram Singh',
    vehicle: 'Bike',
    rating: 4.8,
    totalDeliveries: 1560,
    zone: 'zone-3',
    status: 'offline',
    earnings: 145000,
    image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&h=100&fit=crop',
  },
  {
    id: 'p-4',
    name: 'Priya Verma',
    vehicle: 'Bike',
    rating: 4.6,
    totalDeliveries: 750,
    zone: 'zone-4',
    status: 'available',
    earnings: 72000,
    image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&h=100&fit=crop',
  },
  {
    id: 'p-5',
    name: 'Arjun Patel',
    vehicle: 'Bike',
    rating: 4.9,
    totalDeliveries: 2100,
    zone: 'zone-1',
    status: 'available',
    earnings: 198000,
    image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&h=100&fit=crop',
  },
  {
    id: 'p-6',
    name: 'Sanjay Das',
    vehicle: 'Bike',
    rating: 4.5,
    totalDeliveries: 620,
    zone: 'zone-2',
    status: 'busy',
    earnings: 58000,
    image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&h=100&fit=crop',
  },
  {
    id: 'p-7',
    name: 'Neha Gupta',
    vehicle: 'Bike',
    rating: 4.8,
    totalDeliveries: 1380,
    zone: 'zone-3',
    status: 'available',
    earnings: 132000,
    image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&h=100&fit=crop',
  },
  {
    id: 'p-8',
    name: 'Rohan Mishra',
    vehicle: 'Bike',
    rating: 4.7,
    totalDeliveries: 950,
    zone: 'zone-4',
    status: 'offline',
    earnings: 92000,
    image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&h=100&fit=crop',
  },
  {
    id: 'p-9',
    name: 'Divya Nair',
    vehicle: 'Bike',
    rating: 4.9,
    totalDeliveries: 1920,
    zone: 'zone-1',
    status: 'available',
    earnings: 178000,
    image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&h=100&fit=crop',
  },
  {
    id: 'p-10',
    name: 'Manoj Kumar',
    vehicle: 'Bike',
    rating: 4.6,
    totalDeliveries: 820,
    zone: 'zone-2',
    status: 'available',
    earnings: 78000,
    image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&h=100&fit=crop',
  },
  {
    id: 'p-11',
    name: 'Ravi Singh',
    vehicle: 'Bike',
    rating: 4.8,
    totalDeliveries: 1650,
    zone: 'zone-3',
    status: 'busy',
    earnings: 155000,
    image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&h=100&fit=crop',
  },
  {
    id: 'p-12',
    name: 'Ananya Reddy',
    vehicle: 'Bike',
    rating: 4.7,
    totalDeliveries: 1120,
    zone: 'zone-4',
    status: 'available',
    earnings: 105000,
    image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&h=100&fit=crop',
  },
  {
    id: 'p-13',
    name: 'Karan Dhillon',
    vehicle: 'Bike',
    rating: 4.9,
    totalDeliveries: 2340,
    zone: 'zone-1',
    status: 'offline',
    earnings: 218000,
    image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&h=100&fit=crop',
  },
  {
    id: 'p-14',
    name: 'Pooja Chauhan',
    vehicle: 'Bike',
    rating: 4.5,
    totalDeliveries: 680,
    zone: 'zone-2',
    status: 'available',
    earnings: 65000,
    image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&h=100&fit=crop',
  },
  {
    id: 'p-15',
    name: 'Saurav Pandey',
    vehicle: 'Bike',
    rating: 4.8,
    totalDeliveries: 1580,
    zone: 'zone-3',
    status: 'available',
    earnings: 148000,
    image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&h=100&fit=crop',
  },
  {
    id: 'p-16',
    name: 'Meera Singh',
    vehicle: 'Bike',
    rating: 4.6,
    totalDeliveries: 920,
    zone: 'zone-4',
    status: 'busy',
    earnings: 88000,
    image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&h=100&fit=crop',
  },
  {
    id: 'p-17',
    name: 'Nikhil Verma',
    vehicle: 'Bike',
    rating: 4.9,
    totalDeliveries: 2050,
    zone: 'zone-1',
    status: 'available',
    earnings: 192000,
    image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&h=100&fit=crop',
  },
  {
    id: 'p-18',
    name: 'Anjali Patel',
    vehicle: 'Bike',
    rating: 4.7,
    totalDeliveries: 1240,
    zone: 'zone-2',
    status: 'offline',
    earnings: 118000,
    image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&h=100&fit=crop',
  },
  {
    id: 'p-19',
    name: 'Sachin Nair',
    vehicle: 'Bike',
    rating: 4.8,
    totalDeliveries: 1780,
    zone: 'zone-3',
    status: 'available',
    earnings: 168000,
    image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&h=100&fit=crop',
  },
  {
    id: 'p-20',
    name: 'Zoya Khan',
    vehicle: 'Bike',
    rating: 4.6,
    totalDeliveries: 1050,
    zone: 'zone-4',
    status: 'available',
    earnings: 98000,
    image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&h=100&fit=crop',
  },
];
